// Generated by FADE's GameEventAudioGenerator. Refresh after editing GameEvents; do not edit this file by hand.
using System;
using System.Collections.Generic;
namespace Scarlet.Audio
{
    public static partial class GameEventCatalog
    {
        static partial void AddGeneratedEntries(List<Entry> result)
        {
        }
    }
}
